# Generated by Django 4.2.1 on 2023-06-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('puntuacion', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'programador',
            },
        ),
    ]
